import re
f = 'chapter-7-rebuilding-the-engine-evidence-based-gut-support.html'
html = open(f, encoding='utf-8').read()
def repl(old, new, count=1):
    global html
    assert html.count(old) >= 1, f"NOT FOUND: {old[:80]!r}"
    html = html.replace(old, new, count)

# ---- Butyrate section: expand coaching translation ----
old = '''<p>In real life, this means the single most mechanistically grounded thing you can do for your gut barrier is keep your butyrate-producing bacteria fed. They eat fiber. No fiber, no butyrate, no fuel for the wall. You cannot meaningfully shortcut this with a pill that skips the fermentation step, which is exactly why the nutrition pillar comes first. Practical takeaway: before you buy anything, ask whether you are actually feeding the engine that does the repairing.</p>
  </section>'''
new = '''<p>In real life, this means the single most mechanistically grounded thing you can do for your gut barrier is keep your butyrate-producing bacteria fed. They eat fiber. No fiber, no butyrate, no fuel for the wall. You cannot meaningfully shortcut this with a pill that skips the fermentation step, which is exactly why the nutrition pillar comes first. Practical takeaway: before you buy anything, ask whether you are actually feeding the engine that does the repairing.</p>
    <p>There is a second reason to lead with the engine, and it is about how you talk to people. When you can name the mechanism, you change the conversation from belief to biology. "Eat more fiber, it is good for you" invites argument, because it sounds like generic advice and everyone has heard it. "The cells that hold your gut wall together run mostly on a fuel your own bacteria make out of fiber, and without the fiber they run low" is a different kind of sentence. It is checkable, it is specific, and it reframes a vegetable as engine maintenance rather than a moral obligation. Coaches who can hold the mechanism lightly and explain it plainly tend to get far more durable behavior change than coaches who issue rules, because a person who understands why a thing works can adapt it to their own life when the rule does not fit.</p>
    <p>Notice, too, what the engine framing protects you against. It immunizes you against the entire genre of product that promises to deliver the benefit while skipping the work. If the benefit comes from a molecule your bacteria make in the colon out of fermentable fiber, then any product claiming to hand you that benefit without the fiber and the bacteria is making an extraordinary claim and needs extraordinary evidence. Usually it does not have it. Keep the engine in view and most of the aisle organizes itself for you: the things that feed it or protect it are worth attention, and the things that promise to bypass it deserve a hard, skeptical look.</p>
  </section>'''
repl(old, new)

# ---- Fiber-is-not-one-thing: add McRorie depth ----
old = '''<p>The bigger picture is striking. Fu and colleagues (2022) frame our modern fiber deficit as a centuries-long decline that has tracked with the rise of metabolic disease. Different fibers selectively feed different microbes, raise microbial diversity, and increase short-chain fatty acid production, all of which connect to lower metabolic disease risk. The headline is not "eat more of one magic fiber." It is "eat more kinds of plants, consistently, over time."</p>'''
new = '''<p>The bigger picture is striking. Fu and colleagues (2022) frame our modern fiber deficit as a centuries-long decline that has tracked with the rise of metabolic disease. Different fibers selectively feed different microbes, raise microbial diversity, and increase short-chain fatty acid production, all of which connect to lower metabolic disease risk. The headline is not "eat more of one magic fiber." It is "eat more kinds of plants, consistently, over time."</p>
    <p>It is worth getting more precise about the kinds, because this is exactly the place where supplement marketing exploits a gap in most people's understanding. According to PubMed, McRorie and Fagerberg (2017) lay out an evidence-based framework for fiber supplements that turns on a handful of physical properties: whether a fiber is soluble or insoluble, how viscous and gel-forming it is, and whether and how fast it ferments. Those properties, not the word "fiber" on the label, determine what a fiber actually does in the body. A viscous, gel-forming, poorly-fermented fiber like psyllium is genuinely good at the mechanical jobs, normalizing stool form in both constipation and loose stools, and modestly lowering cholesterol and blood glucose, precisely because it holds water and forms a gel rather than because it feeds bacteria. A readily fermented fiber like inulin does the opposite kind of work: it is excellent food for the microbiome and a strong driver of short-chain fatty acid production, but because it ferments fast it is also the one most likely to produce gas and bloating if you ramp it too quickly.</p>
    <p>This distinction matters more than almost any supplement choice, because it explains why two people taking "a fiber supplement" can have completely opposite experiences, and why generic advice to "add fiber" sometimes backfires badly. The person with constipation who needs bulk and water-holding wants a gel-forming fiber. The person trying to feed a depleted microbiome wants fermentable fibers, introduced slowly. The person with a sensitive, symptomatic gut may need to be careful with exactly the fast-fermenting fibers that the wellness internet pushes hardest. McRorie and Fagerberg's (2017) practical point is that most products on the shelf do not actually have the physical characteristics that drive the documented benefits, which is a polite way of saying a lot of fiber marketing is selling a category word rather than a mechanism. As a coach, the useful move is not to recommend a brand but to help a person match the property of the fiber to the job they are trying to do, and, when symptoms are involved, to send them to a clinician or dietitian rather than guess.</p>'''
repl(old, new)

open(f, 'w', encoding='utf-8').write(html)
body=re.sub(r'<script.*?</script>','',html,flags=re.S); body=re.sub(r'<style.*?</style>','',body,flags=re.S)
print('words:', len(re.sub(r'<[^>]+>',' ',body).split()))
print('em-dashes:', html.count(chr(8212)))
