import re
f = 'chapter-7-rebuilding-the-engine-evidence-based-gut-support.html'
html = open(f, encoding='utf-8').read()
def repl(old, new, count=1):
    global html
    assert html.count(old) >= 1, f"NOT FOUND: {old[:80]!r}"
    html = html.replace(old, new, count)

# ---- Probiotics: add strain-specificity + definition (Hill 2014) after existing probiotic paragraph ----
old = '''<p>That is a real signal, and we should say so plainly. But read the authors' own caveat, because it is the responsible part. They note that further high-quality RCTs are still needed for definitive conclusions. Here is why that matters in practice. "Probiotics work" is not a single claim, because probiotics are not a single product. Effects are strain-specific and condition-specific. A strain that fortifies the barrier in an inflamed population may do little measurable for a healthy person with no barrier problem. The meta-analysis tells you the category can fortify a compromised barrier; it does not tell you that any random bottle will help any random person.</p>'''
new = '''<p>That is a real signal, and we should say so plainly. But read the authors' own caveat, because it is the responsible part. They note that further high-quality RCTs are still needed for definitive conclusions. Here is why that matters in practice. "Probiotics work" is not a single claim, because probiotics are not a single product. Effects are strain-specific and condition-specific. A strain that fortifies the barrier in an inflamed population may do little measurable for a healthy person with no barrier problem. The meta-analysis tells you the category can fortify a compromised barrier; it does not tell you that any random bottle will help any random person.</p>
    <p>To use probiotics intelligently you have to understand what the word even means, because the consumer use of it is far looser than the scientific one. According to PubMed, Hill and colleagues (2014), writing as the expert consensus panel of the International Scientific Association for Probiotics and Prebiotics, defined a probiotic precisely: live microorganisms that, when administered in adequate amounts, confer a health benefit on the host. Every part of that sentence is load-bearing and routinely violated by marketing. "Live" means dead bacteria in a poorly stored product do not count. "Adequate amounts" means dose matters and a sprinkle is not a probiotic. And "confer a health benefit," demonstrated for that specific strain at that specific dose, is the part most products skip entirely, gesturing at the general glow of the word rather than at evidence for what is actually in the capsule.</p>
    <p>The single most important consequence of the Hill consensus, for a coach, is that benefits are demonstrated at the level of the strain, not the species and certainly not the category. This is not a technicality. The same species can contain strains with completely different effects, the way two dogs of the same breed can have opposite temperaments. A strain such as <em>Lacticaseibacillus rhamnosus</em> GG is one of the most studied probiotics in existence, with a body of trials behind specific uses such as certain forms of acute diarrhea, and it adheres well to intestinal mucus, which is part of why it persists long enough to act. None of that evidence transfers automatically to a different <em>L. rhamnosus</em> strain, let alone to a generic "Lactobacillus blend" with no strain designation on the label at all. When a product will not even tell you the strain, in the standard genus-species-strain notation, it is telling you that there is probably no strain-specific evidence to point to. The practical filter is blunt and useful: no named strain, no claim worth believing.</p>'''
repl(old, new)

# ---- Prebiotics: add Gibson 2017 definition ----
old = '''<p>Prebiotics are the fibers and compounds that feed your existing beneficial bacteria, and conceptually they sit closer to the nutrition pillar than to the pill aisle. The logic is sound and ties straight back to the butyrate engine: feed the fermenters, get more SCFAs, support the barrier. The honest framing is that for most people, "prebiotic" is just a more expensive word for "the fermentable fiber you could be getting from food." A prebiotic supplement is a reasonable tool when food intake is genuinely hard to raise, not a substitute for a varied plant-forward diet.</p>'''
new = '''<p>Prebiotics are the fibers and compounds that feed your existing beneficial bacteria, and conceptually they sit closer to the nutrition pillar than to the pill aisle. The logic is sound and ties straight back to the butyrate engine: feed the fermenters, get more SCFAs, support the barrier. According to PubMed, Gibson and colleagues (2017), again as the ISAPP consensus panel, defined a prebiotic as a substrate that is selectively utilized by host microorganisms to confer a health benefit. The word "selectively" is the key. A prebiotic is not just any fiber; it is one your beneficial microbes preferentially use. That precision matters because, just as with probiotics, the label "prebiotic" gets slapped on products with thin justification, and a coach who knows the real definition can ask the obvious question: selectively utilized by what, to confer what benefit, on what evidence.</p>
    <p>The honest framing is that for most people, "prebiotic" is just a more expensive word for "the fermentable fiber you could be getting from food." Onions, garlic, leeks, oats, slightly green bananas, cooled cooked potatoes, beans, and asparagus are loaded with the very compounds, inulin and resistant starch and their relatives, that the supplement version isolates and sells back to you. A prebiotic supplement is a reasonable tool when food intake is genuinely hard to raise, and it can be a precise instrument in a clinical setting under guidance, but for a generally healthy person it is rarely doing anything a more varied plate would not do for less money. And because prebiotics are by definition fast-fermenting food for bacteria, they carry the same caveat as fermentable fiber: ramp them too fast in a sensitive gut and you will manufacture exactly the bloating you were trying to fix.</p>'''
repl(old, new)

# ---- Add product-quality reality (Mazzantini 2021) after the toolkit-in-perspective section, before its coaching translation ----
old = '''    <h3>Coaching translation</h3>
    <p>Here is where people get this wrong, plainly: they buy the supplement to compensate for the foundation they are skipping.'''
new = '''    <h3>The part the label does not tell you: product quality</h3>
    <p>There is a problem with probiotic supplements that has nothing to do with whether the underlying science is sound, and it is one of the most important things a coach can flag, because it is invisible at the point of sale. Even granting that a particular strain has good evidence behind it, you still have to ask whether the bottle actually contains that strain, alive, in the dose claimed, on the day you swallow it. The answer is often no. According to PubMed, Mazzantini and colleagues (2021) analyzed the compositional quality of probiotic formulations marketed worldwide and found a sobering pattern: a substantial share of products did not match their own labels, with viable cell counts below the declared amount, species that did not correspond to what was listed, and in some cases organisms that should not have been there at all. Other quality surveys have found similar gaps, with a large fraction of products delivering fewer live organisms than promised.</p>
    <p>This matters enormously and it reframes the whole probiotic conversation. Probiotics, in most markets, are regulated as dietary supplements rather than as drugs, which means the burden of proof and the manufacturing oversight are far lighter than people assume. There is no pre-market requirement to prove the product works, and verification that the label is accurate is inconsistent at best. So even the consumer who does everything right, picks an evidence-backed strain, at an adequate dose, for an appropriate reason, can be undone by a product that simply does not contain what it says. The practical defenses are modest but real: look for the full genus-species-strain designation, look for a dose guaranteed through the end of shelf life rather than only "at time of manufacture," check storage requirements, and favor products that have undergone independent third-party testing. None of this is something a coach can verify for a client, which is itself the point. When the product category cannot reliably guarantee its own contents, that is a strong argument for leaning on the foundation, where the "product" is food and sleep and movement and there is no label to be wrong.</p>
    <aside class="ch-callout">
      <div class="ch-callout-label">Think About It</div>
      <p>Mazzantini et al. found many probiotic products did not contain what their labels claimed. How does that finding change the way you would talk to someone who is convinced a specific bottle "isn't working," before you ever discuss whether the strain itself has evidence?</p>
    </aside>

    <h3>Coaching translation</h3>
    <p>Here is where people get this wrong, plainly: they buy the supplement to compensate for the foundation they are skipping.'''
repl(old, new)

open(f, 'w', encoding='utf-8').write(html)
body=re.sub(r'<script.*?</script>','',html,flags=re.S); body=re.sub(r'<style.*?</style>','',body,flags=re.S)
print('words:', len(re.sub(r'<[^>]+>',' ',body).split()))
print('em-dashes:', html.count(chr(8212)))
print('callouts:', html.count('ch-callout-label'))
