import re
f = 'chapter-7-rebuilding-the-engine-evidence-based-gut-support.html'
html = open(f, encoding='utf-8').read()
def repl(old, new, count=1):
    global html
    assert html.count(old) >= 1, f"NOT FOUND: {old[:80]!r}"
    html = html.replace(old, new, count)

# ---- Deepen stress coaching translation (add a paragraph) ----
old = '''<p>This is why it matters: stress regulation belongs in the same category as fiber, not in a separate "lifestyle" bucket you get to skip. You do not need a perfect meditation practice. You need a few reliable downshifts in your day that pull you out of sustained sympathetic activation: slow breathing, a real walk, time without a screen, predictable wind-downs. The point is dose and consistency, not intensity. In practice, this means treating chronic stress as a measurable input to gut repair, and treating "I'm too busy to manage stress" as roughly equivalent to "I'm too busy to fuel the engine." Where stress crosses into clinical anxiety, depression, or trauma, that is firmly beyond a coach's scope and into professional care.</p>'''
new = '''<p>This is why it matters: stress regulation belongs in the same category as fiber, not in a separate "lifestyle" bucket you get to skip. You do not need a perfect meditation practice. You need a few reliable downshifts in your day that pull you out of sustained sympathetic activation: slow breathing, a real walk, time without a screen, predictable wind-downs. The point is dose and consistency, not intensity. In practice, this means treating chronic stress as a measurable input to gut repair, and treating "I'm too busy to manage stress" as roughly equivalent to "I'm too busy to fuel the engine." Where stress crosses into clinical anxiety, depression, or trauma, that is firmly beyond a coach's scope and into professional care.</p>
    <p>There is a subtler coaching skill buried here, which is helping people see that the gut and the nervous system are running a conversation they can actually feel, if they pay attention. Many people have noticed that their digestion falls apart during a stressful week and never connected the two, because nobody told them the link was real and physical. When you give them the mechanism, that the stress response literally degranulates mast cells in the gut wall and shifts motility and secretion, the bloating before a big meeting stops feeling like a personal failing and starts feeling like predictable physiology. That reframe is therapeutic in itself. It moves a person from "something is wrong with me" to "my body is doing exactly what bodies do under load, and here is the lever." The lever is not a supplement. It is downshifting the load, and that is squarely inside what a coach can help with, right up to the boundary where distress becomes a clinical matter that belongs with a licensed professional.</p>
    <p>Be honest, too, about the limits of what we can claim here. The stress-to-barrier mechanism is well supported in the reviews we have cited, but "do a breathing practice and your leaky gut will heal" is a claim that runs well past the evidence, and you should not make it. What you can say is grounded and still motivating: chronic sympathetic overdrive is a documented input to barrier disruption and dysbiosis, regulating it is low-risk and broadly beneficial, and it is upstream of the same repair machinery as everything else in this chapter. That is a true sentence. The cure-promise version is not, and the difference between those two sentences is most of what separates responsible coaching from the wellness theater we keep flagging.</p>'''
repl(old, new)

# ---- Deepen sleep coaching translation ----
old = '''<p>Here is the honest framing. Sleep is not a soft extra you address after the supplements. For the gut barrier specifically, it may be the highest-leverage single change for an under-slept person, because it is upstream of butyrate production, mucus, and tight junctions simultaneously. In practice, this means if someone is sleeping six hours and asking which probiotic to buy, the answer is almost always "let's find you an extra hour of sleep first." Regular timing, a dark cool room, and a real wind-down beat any bottle on the shelf for this person. Persistent insomnia or sleep apnea, of course, is a medical issue, not a coaching one.</p>
  </section>'''
new = '''<p>Here is the honest framing. Sleep is not a soft extra you address after the supplements. For the gut barrier specifically, it may be the highest-leverage single change for an under-slept person, because it is upstream of butyrate production, mucus, and tight junctions simultaneously. In practice, this means if someone is sleeping six hours and asking which probiotic to buy, the answer is almost always "let's find you an extra hour of sleep first." Regular timing, a dark cool room, and a real wind-down beat any bottle on the shelf for this person. Persistent insomnia or sleep apnea, of course, is a medical issue, not a coaching one.</p>
    <p>The reason sleep is such a high-leverage target, and such an underused one, is that it is simultaneously the most powerful lever and the one people most readily sacrifice. Nobody brags about skipping vegetables, but plenty of people wear five-hour nights as a badge of dedication. Part of the coaching work is simply giving people permission, backed by mechanism, to protect their sleep as a non-negotiable rather than the first thing they trade away when life gets busy. When you can tell someone that the same night they cut short is the night their gut was supposed to rebuild its mucus layer and refuel its barrier cells, the trade-off stops looking like discipline and starts looking like what it is, which is borrowing against the system that keeps them well. The Sun and colleagues (2023) review gives you the specifics to make that case credibly, and credibility is what turns "you should sleep more" into a change someone actually makes.</p>
    <p>It is also worth holding the direction of causation loosely, because it runs both ways and that is good news. Poor sleep degrades the gut, and a disrupted, inflamed gut also degrades sleep, which is the same reinforcing loop we keep meeting. The practical upside of a loop is that you can enter it from any side. Improving the gut through the nutrition pillar can improve sleep; improving sleep can improve the gut; calming stress helps both. You do not have to fix everything at once. You have to push on the loop at whatever point a given person can actually move, and let the feedback do some of the work for you.</p>
  </section>'''
repl(old, new)

# ---- NEW SECTION: hydration & movement pillar, inserted before the loop widget ----
old = '''  <hr class="ch-divider">

  <div class="ch-widget" id="loopWidget">'''
new = '''  <hr class="ch-divider">

  <section class="ch-section">
    <h2>The quiet pillars: hydration and movement</h2>
    <p>Two inputs sit alongside nutrition, sleep, and stress in the foundation, and they get less airtime mostly because nobody can sell them at a premium. Water is free and walking is free, which is precisely why the wellness industry has so little to say about them and so much to say about ninety-dollar bottles. That economic fact should make you pay closer attention to them, not less.</p>
    <h3>Hydration: the unglamorous mechanic of stool form</h3>
    <p>Start with water, because the claims around it are a useful test case in evidence-reading. You will hear, on one side, that drinking more water flushes toxins, fixes digestion, and cures constipation, and on the other side a smug correction that hydration "does nothing" unless you are clinically dehydrated. As usual, the honest answer is in between and depends on who you are talking about. According to PubMed, Anti and colleagues (1998) ran a controlled trial in adults with functional constipation: everyone ate roughly 25 grams of fiber a day, but one group was assigned to drink about two liters of fluid daily while the other drank as they pleased. Both groups improved, because the fiber was doing real work, but the group drinking more water had a significantly greater increase in stool frequency and a greater drop in laxative use. The water made the fiber work better.</p>
    <p>Read that result carefully, because it is a model of the kind of nuance this chapter is training you to hold. Water is not a cure-all and it is not nothing. It is a cofactor. Fermentable and gel-forming fibers need water to do their jobs; a bulking fiber with no water to hold becomes a brick rather than a soft, easy stool. This is also why the common advice to "add fiber" can backfire when someone adds the fiber but not the fluid and ends up more constipated, not less. The mechanism is mundane and exactly that mundane mechanism is what makes the claim trustworthy. For someone with genuinely low fluid intake and sluggish bowels, getting fluid up to a sensible level alongside fiber is one of the cheapest wins available. For someone already well-hydrated, pouring in extra liters does little, and chasing a gallon-a-day target for its own sake is its own small piece of wellness theater.</p>
    <h3>Movement: feeding the butyrate producers from a different direction</h3>
    <p>Movement earns its place in the foundation for a reason that ties straight back to the engine. According to PubMed, Monda and colleagues (2017) reviewed how regular exercise modifies the gut microbiota with measurable health effects: it tends to increase microbial diversity, improve the balance of major bacterial groups, and, most relevant for us, expand the populations of short-chain-fatty-acid producers, including butyrate producers. In other words, movement and a plant-rich diet are pushing on the same machinery from two different angles. Exercise also stimulates motility directly, which is part of why a real walk helps a stalled gut in a way that an extra supplement rarely does.</p>
    <p>Keep the claims proportionate, though, because this is a young literature built largely on cross-sectional and animal work, and the human trials are still catching up. The honest version is that regular, moderate activity is associated with a more diverse, more butyrate-friendly microbiome and better motility, and that it is low-risk and broadly beneficial for reasons that extend far beyond the gut. The dishonest version, which you will see, dresses a few promising studies up as proof that a specific exercise protocol will "rebuild your microbiome." It will not, at least not on the evidence we have. What you can say cleanly is that movement belongs in the foundation, that it works on the same repair biology as the other pillars, and that for most people the right dose is simply regular and sustainable rather than extreme.</p>
    <aside class="ch-callout">
      <div class="ch-callout-label">Think About It</div>
      <p>Water and walking are the two interventions in this chapter with the least money behind them and some of the most plausible mechanisms. How does noticing who profits from a claim, and who does not, help you read the evidence around any gut-health product more clearly?</p>
    </aside>
    <h3>Coaching translation</h3>
    <p>In practice, hydration and movement are the easiest pillars to fold into a plan because they cost nothing and need no shopping. The coaching skill is mostly about proportion and honesty: get fluid to a sensible level especially when raising fiber, build in regular movement a person will actually sustain, and resist the urge to oversell either one. You are not promising a cure. You are pointing out two free, low-risk, mechanistically grounded levers that the industry ignores precisely because there is no margin in them, and helping a person use them. Where bowel changes are new, severe, or accompanied by warning signs, that is a referral, not a hydration tip.</p>
  </section>

  <hr class="ch-divider">

  <div class="ch-widget" id="loopWidget">'''
repl(old, new)

open(f, 'w', encoding='utf-8').write(html)
body=re.sub(r'<script.*?</script>','',html,flags=re.S); body=re.sub(r'<style.*?</style>','',body,flags=re.S)
print('words:', len(re.sub(r'<[^>]+>',' ',body).split()))
print('em-dashes:', html.count(chr(8212)))
print('callouts:', html.count('ch-callout-label'))
